data Error {}

extend self: Error {

    rethrow[T](): T
        target js sync "throw self_"

    name(): String
        target js sync "return self_.name || ''"

    message(): String
        target js sync "return self_.message || ''"

    stack(): String
        target js sync "return self_.stack || ''"

    exception(): Option[Any]
        target js sync "return self_.ffException ? ff_core_Option.Some(self_.ffException) : ff_core_Option.None()"

}
