type Error {}

extend self: Error {

    rethrow[T](): T { panic("magic") }
        target js sync "throw self_"

    name(): String { panic("magic") }
        target js sync "return self_.name || ''"

    message(): String { panic("magic") }
        target js sync "return self_.message || ''"

    stack(): String { panic("magic") }
        target js sync "return self_.stack || ''"

    /*
    as[E: Exception](): Option[E]
    */

}
